### ISSUE TITLE
PointAnnotation doesn't show the Text

### ISSUE THREAD

**Issue by aforoughi1** [HavenDV/H.OxyPlot#1]
Steps to reproduce
The PointAnnotation works under 2.0 but I it doesn't work under 2.1
For example,
```cs
public void Annotation(MarkerType shape, OxyColor color, double size, string text, DataPoint position)
{
    var annotation = new PointAnnotation
    {
        Shape = shape,
        Text = text,
        TextColor = color,
        TextHorizontalAlignment = HorizontalAlignment.Center,
        TextVerticalAlignment = VerticalAlignment.Middle,
        TextMargin = 0,
        TextPosition = position,
        FontWeight = FontWeights.Bold,
        Fill = OxyColors.Transparent,
        Stroke = SetTransparency(200, color),
        StrokeThickness = 2,
        Size = size,
        X = position.X,
        Y = position.Y
    };

    Model.Annotations.Add(annotation);
}
```
To Test it , call
```cs
Annotation(MarkerType.Circle, OxyColors.RoyalBlue, 8, "D", new DataPoint(60, 60));
```
Platform:
.Net 6.0 and WinUI

Expected behaviour
I expected to see a Circle Marker with Letter D inside. However, I only see a Circle with No Text.

If I export it as below , the pdf is correct
```cs
public static void ExportToPDF(this PlotModel model, Stream stream, float w = 1050, float h = 350)
{
    OxyPlot.SkiaSharp.PdfExporter pdfExporter = new OxyPlot.SkiaSharp.PdfExporter { Width = w, Height = h };
    stream.SetLength(0);
    pdfExporter.Export(model, stream);
    stream.Flush();
    stream.Close();
}
```
see the rendered PDF through Skia which suggests the core library is be behaving as expected
[TSCO.L.PDF](https://github.com/HavenDV/H.OxyPlot/files/8031674/TSCO.L.PDF)

The output from WinUI
![Screenshot 2022-02-08 151819](https://user-images.githubusercontent.com/48822519/153178542-57b40f2f-038a-466e-8f2e-66c001226926.png)

**Comment by HavenDV** [comment]
Hello. Thanks for creating this issue.
The first thing I want to note is that this fork is an attempt to generalize the current WPF version of OxyPlot and the abandoned OxyPlot UWP - https://github.com/oxyplot/oxyplot-uwp. I'm sure there are many more issues like this here because the UWP version of OxyPlot hasn't been developed since 2019.
Second, I can fix it, but to save me a little time, you need to prepare a project with a small example of this problem so that I can quickly test a solution to it.

**Comment by aforoughi1** [comment]
I have tried to attached a zip file but it is not allowed.
Let Me know how to send it to you.
Thanks

**Comment by HavenDV** [comment]
Perhaps you forgot to delete the bin and obj directories and the zip file is too big? Github allows you to attach zip files.

**Comment by aforoughi1** [comment]
[App1.zip](https://github.com/HavenDV/H.OxyPlot/files/8036147/App1.zip)

thanks

**Comment by HavenDV** [comment]
Issue fixed, NuGet package should be available in about 10 minutes
