### ISSUE TITLE
WinUI 3 Desktop compatibility

### ISSUE THREAD

**Issue by XamlBrewer** [HavenDV/H.OxyPlot#2]
I'm trying to use H.OxyPlot.WinUI in a WinUI 3 Desktop application. I don't get any errors and all bindings are OK, but the PlotView remains empty. It responds to properties like Height and Background, but it never displays the Model. 

Is it too soon to use this package in this environment?

**Comment by HavenDV** [comment]
https://github.com/HavenDV/H.OxyPlot/issues/1
There are some problems here, as in this issue, but in general everything should work. In your case, I would make sure the Model is visible on other platforms to avoid any bugs.
[App1.zip](https://github.com/HavenDV/H.OxyPlot/files/8036254/App1.zip)

**Comment by XamlBrewer** [comment]
Many thanks for the sample app!

It seems that the PlotView requires a Page or a Frame in its uplevel XAML tree. I was hosting it inside the main Window, and there it doesn't seem to respond to the Model. I'm not sure if this is a bug or just something that should be mentioned in the docs.

**Comment by HavenDV** [comment]
I think the problem is that Window doesn't have a DataContext
It works for me for single MainWindow app:
```xml
<Window
    x:Class="App1.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:App1"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    xmlns:oxy="using:OxyPlot"
    >
    <Page>
        <Page.DataContext>
            <local:ModelView />
        </Page.DataContext>
        <oxy:PlotView Model="{Binding Model}" />
    </Page>
</Window>
```

**Comment by XamlBrewer** [comment]
You need to have the Page element indeed. DataContext is not needed when you use {x:Bind} 
I went for this (sorry for the image, code formatting did not work well):
![image](https://user-images.githubusercontent.com/9828352/153385100-d41d69f0-102e-4e7d-a8fd-7c4900c4cce8.png)

Remove the Page element, and the Model disappears. This behavior is different from other controls, but yes: the root cause is Window not having a DataContext: https://github.com/microsoft/microsoft-ui-xaml/issues/2687
