### ISSUE TITLE
Axis lines are not drawn

### ISSUE THREAD

**Issue by XamlBrewer** [HavenDV/H.OxyPlot#5]
If you make the _PlotAreaBorderColor_ transparent, then you notice that not a single axis line is drawn. Setting an _AxislineColor_ has no effect. This applies to all types, so it is not the same issue as #4. I don't see anyone observing this in the base OxyPlot repo. Here's a screenshot from my [sample repo here](https://github.com/XamlBrewer/XamlBrewer.WinUI3.OxyPlot.Sample):

![MissingAxes](https://user-images.githubusercontent.com/9828352/153714431-13f25673-26d7-4aea-9abc-fcfba1a44eea.png)

**Comment by HavenDV** [comment]
Sorry I don't understand the expected behavior in this case

I'm testing the behavior on the official WPF version:

with `model.PlotAreaBorderColor = OxyColors.Transparent;`
![image](https://user-images.githubusercontent.com/3002068/153739279-0922b4ea-0b4b-4d1b-a084-088cf282e38a.png)

without `model.PlotAreaBorderColor = OxyColors.Transparent;`
![image](https://user-images.githubusercontent.com/3002068/153739574-492a10a4-9497-4122-ba10-75221119f6a4.png)

Can you point me if there is a problem in these screenshots?
If so, then you need to create an issue at https://github.com/oxyplot/oxyplot to fix it on all platforms.
At the moment, I support the UWP/WinUI/Uno platforms of this library, trying to match the WPF behavior of the main library with some of my own additions (like Dark Theme support).

**Comment by HavenDV** [comment]
But I definitely see a bug here :)
![image](https://user-images.githubusercontent.com/3002068/153739626-669c2592-9b5d-44b6-a587-6407f9a06241.png)

P.S. Fixed

**Comment by HavenDV** [comment]
@VisualMelon please check this issue

**Comment by XamlBrewer** [comment]
What I was expecting, is that there would be no border but axis lines would remain visible - as in the following screenshot from UWP:

![Clustering](https://user-images.githubusercontent.com/9828352/153744182-dd49ba68-05de-4133-88f0-f86aaa69d259.png)

**Comment by HavenDV** [comment]
Perhaps there is some configuration problem here? Because I wasn't able to achieve this behavior in WPF with any of the versions of OxyPlot.WPF.
Also, I couldn't find the `AxislineColor` property. What class is it in?

**Comment by XamlBrewer** [comment]
It's in the OxyPlot.Axes.Axis class (oxyplot.core\2.1.0\lib\netstandard2.0\OxyPlot.dll).

This is the corresponding code from my [Theming ](https://github.com/XamlBrewer/XamlBrewer.WinUI3.OxyPlot.Sample/blob/master/XamlBrewer.WinUI3.OxyPlot.Sample/Views/ThemingPage.xaml.cs) sample (currently line 180):
axis.TicklineColor = OxyColors.DimGray;
axis.AxislineColor = OxyColors.Red; // Doesn't seem to work.

**Comment by XamlBrewer** [comment]
> But I definitely see a bug here :) ![image](https://user-images.githubusercontent.com/3002068/153739626-669c2592-9b5d-44b6-a587-6407f9a06241.png)
> 
> P.S. Fixed

Indeed fixed the Contour series, but now the PieChart has an issue:
![PieChartLines](https://user-images.githubusercontent.com/9828352/153750190-bb8a9ddd-24dd-4a38-b03d-d401428b1776.png)

**Comment by HavenDV** [comment]
Thanks for the info, I'll see what I can do tomorrow.

**Comment by VisualMelon** [comment]
The default for `AxislineStyle` is `LineStyle.None`: you need to set that to e.g. `AxislineStyle = LineStyle.Solid` if you set the `AxisLineColor` also (which by default is black).

See for example https://github.com/oxyplot/oxyplot/blob/develop/Source/Examples/ExampleLibrary/Axes/AxisExamples.cs#L196

**Comment by XamlBrewer** [comment]
This means that the behavior is as intended, so the issue may be closed. Sorry to have bothered you with this one, @HavenDV.

**Comment by HavenDV** [comment]
> Indeed fixed the Contour series, but now the PieChart has an issue:

Pie issue is a regression caused by the recent application of the PolyLineSegment workaround https://github.com/oxyplot/oxyplot/issues/1848
I will investigate whether it is possible to solve all the problems at the same time.

**Comment by HavenDV** [comment]
I reverted the PolyLineSegment fix, Pie should work correctly. But the issue shown here - https://github.com/oxyplot/oxyplot/issues/1848 will come back
But there the main reason is problems on the WinUI side - https://github.com/microsoft/microsoft-ui-xaml/issues/6716
