### ISSUE TITLE
Question: Is a PlotView/PlotModel suppposed to work in a (filteted) ListView

### ISSUE THREAD

**Issue by mibuehrer** [HavenDV/H.OxyPlot#6]
### Describe the bug

I have a couple of objects (each with a PlotModel) in a ListView. This seems to work ok. But as soon as I apply a filter, I get an exception: _This PlotModel is already in use by another PlotView control._
I am new to this, but for me it sounds like a PlotView is getting reused without destroying the binding to the previous binding.

Q.: Is this scenario  not supposed to work at all? Am I doing something wrong? 

In case you need more information, please let me know.

P.S.: Because my project is WinUI 3, i can't say wether this behaviour is different in the original Oxyplot or not

### Steps to reproduce the bug

in the xaml:

                <ListView x:Name="FolderListView"
                  ItemsSource="{x:Bind ViewModel.Channels, Mode=OneWay}"
                    <ListView.ItemTemplate>
                        <DataTemplate x:DataType="vm:chanItem">
                                        <oxy:PlotView Model="{x:Bind Model}" Height="200"/>
                        </DataTemplate>
                    </ListView.ItemTemplate>
                </ListView>

In the ViewModel  there is a ObservableCollection<chanItem>:

`public ObservableCollection<chanItem> Channels
        {
            get
            {
                if (hasFilter())
                {
                    var flt = getFilter();
                    return new ObservableCollection<chanItem>(channels.Where(i => i.filter(flt)));
                }
                else
                {
                    return channels;
                }
            }
        }`
And the chanItem has oxy:PlotModel Model (I think any Model will do)

### Platform

WinUI

### IDE

Visual Studio 2022

**Comment by HavenDV** [comment]
I think you need to ask it here - https://github.com/oxyplot/oxyplot/issues. I don't think the problem is platform specific.

**Comment by mibuehrer** [comment]
Thank you. I didn't find issue 497 before - don't ask me why. I'll close this issue
